// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "playerSprite":return img`
5 5 5 5 5 
8 8 5 8 8 
8 8 5 8 8 
8 8 5 8 8 
5 5 5 5 5 
`;
            case "image2":
            case "ghostLeft":return img`
........................
........................
........................
........................
..........fffff.........
........ff1111bff.......
.......fb1111111bf......
.......f111111111f......
......fd1111111ffff.....
......fd111dd1c111bf....
......fb11fcdf1b1bff....
......f11111bfbfbff.....
......f1b1bdfcffff......
......fbfbfcfcccf.......
......ffffffffff........
.........ffffff.........
.........ffffff.........
.........fffffff..f.....
..........fffffffff.....
...........fffffff......
........................
........................
........................
........................
`;
            case "image3":
            case "ghostRight":return img`
........................
........................
........................
........................
.........fffff..........
.......ffb1111ff........
......fb1111111bf.......
......f111111111f.......
.....ffff1111111df......
....fb111c1dd111df......
....ffb1b1fdcf11bf......
.....ffbfbfb11111f......
......ffffcfdb1b1f......
.......fcccfcfbfbf......
........ffffffffff......
.........ffffff.........
.........ffffff.........
.....f..fffffff.........
.....fffffffff..........
......fffffff...........
........................
........................
........................
........................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
